// <auto-generated />
using System;
using System.Collections.Generic;
using CustomCADs.Orders.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomCADs.Orders.Persistence.Migrations
{
    [DbContext(typeof(OrdersContext))]
    [Migration("20241113145912_Initial_Migration")]
    partial class Initial_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Orders")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomCADs.Orders.Domain.Cads.Cad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClientId");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Path");

                    b.ComplexProperty<Dictionary<string, object>>("CamCoordinates", "CustomCADs.Orders.Domain.Cads.Cad.CamCoordinates#Coordinates", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("X")
                                .HasColumnType("int")
                                .HasColumnName("CamX");

                            b1.Property<int>("Y")
                                .HasColumnType("int")
                                .HasColumnName("CamY");

                            b1.Property<int>("Z")
                                .HasColumnType("int")
                                .HasColumnName("CamZ");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PanCoordinates", "CustomCADs.Orders.Domain.Cads.Cad.PanCoordinates#Coordinates", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("X")
                                .HasColumnType("int")
                                .HasColumnName("PanX");

                            b1.Property<int>("Y")
                                .HasColumnType("int")
                                .HasColumnName("PanY");

                            b1.Property<int>("Z")
                                .HasColumnType("int")
                                .HasColumnName("PanZ");
                        });

                    b.HasKey("Id");

                    b.ToTable("Cads", "Orders");
                });

            modelBuilder.Entity("CustomCADs.Orders.Domain.CustomOrders.CustomOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BuyerId");

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DeliveryType");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<Guid?>("DesignerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DesignerId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("OrderDate");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OrderStatus");

                    b.ComplexProperty<Dictionary<string, object>>("Image", "CustomCADs.Orders.Domain.CustomOrders.CustomOrder.Image#Image", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ImagePath");
                        });

                    b.HasKey("Id");

                    b.ToTable("CustomOrders", "Orders");
                });

            modelBuilder.Entity("CustomCADs.Orders.Domain.GalleryOrders.Entities.GalleryOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GalleryOrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GalleryOrderId");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProductId");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PurchaseDate");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.ComplexProperty<Dictionary<string, object>>("Price", "CustomCADs.Orders.Domain.GalleryOrders.Entities.GalleryOrderItem.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PriceCurrency");

                            b1.Property<int>("Precision")
                                .HasColumnType("int")
                                .HasColumnName("PricePrecision");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PriceSymbol");
                        });

                    b.HasKey("Id");

                    b.HasIndex("GalleryOrderId");

                    b.ToTable("GalleryOrderItems", "Orders");
                });

            modelBuilder.Entity("CustomCADs.Orders.Domain.GalleryOrders.GalleryOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BuyerId");

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DeliveryType");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PurchaseDate");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.HasKey("Id");

                    b.ToTable("GalleryOrders", "Orders");
                });

            modelBuilder.Entity("CustomCADs.Orders.Domain.Shipments.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClientId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "CustomCADs.Orders.Domain.Shipments.Shipment.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Country");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Street");
                        });

                    b.HasKey("Id");

                    b.ToTable("Shipments", "Orders");
                });

            modelBuilder.Entity("CustomCADs.Orders.Domain.GalleryOrders.Entities.GalleryOrderItem", b =>
                {
                    b.HasOne("CustomCADs.Orders.Domain.GalleryOrders.GalleryOrder", "GalleryOrder")
                        .WithMany("Items")
                        .HasForeignKey("GalleryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GalleryOrder");
                });

            modelBuilder.Entity("CustomCADs.Orders.Domain.GalleryOrders.GalleryOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
