global using CustomCADs.Carts.Application.ActiveCarts.Dtos;
global using CustomCADs.Carts.Application.PurchasedCarts.Dtos;
global using CustomCADs.Carts.Endpoints.ActiveCarts.Dtos;
global using CustomCADs.Carts.Endpoints.PurchasedCarts.Dtos;
global using CustomCADs.Shared.Abstractions.Requests.Sender;
global using CustomCADs.Shared.API;
global using CustomCADs.Shared.Core;
global using FastEndpoints;
global using Microsoft.AspNetCore.Http;
