global using CustomCADs.Printing.Application.Customizations.Dtos;
global using CustomCADs.Printing.Application.Materials.Dtos;
global using CustomCADs.Printing.Endpoints.Customizations.Dtos;
global using CustomCADs.Shared.Abstractions.Requests.Sender;
global using CustomCADs.Shared.API;
global using CustomCADs.Shared.Core;
global using CustomCADs.Shared.Core.Common.TypedIds.Printing;
global using FastEndpoints;
global using Microsoft.AspNetCore.Http;
