global using CustomCADs.Customizations.Application.Customizations.Dtos;
global using CustomCADs.Customizations.Application.Materials.Dtos;
global using CustomCADs.Customizations.Domain.Customizations;
global using CustomCADs.Customizations.Domain.Materials;
global using CustomCADs.Shared.Abstractions.Requests.Commands;
global using CustomCADs.Shared.Abstractions.Requests.Queries;
global using CustomCADs.Shared.Core;
global using CustomCADs.Shared.Core.Common.Exceptions.Application;
global using CustomCADs.Shared.Core.Common.TypedIds.Customizations;