// <auto-generated />
using System;
using CustomCADs.Idempotency.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomCADs.Idempotency.Persistence.Migrations
{
    [DbContext(typeof(IdempotencyContext))]
    partial class IdempotencyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Idempotency")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomCADs.Idempotency.Domain.IdempotencyKeys.IdempotencyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestHash")
                        .HasColumnType("text")
                        .HasColumnName("RequestHash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("ResponseBody");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("StatusCode");

                    b.HasKey("Id", "RequestHash");

                    b.HasIndex("CreatedAt");

                    b.ToTable("IdempotencyKeys", "Idempotency");
                });
#pragma warning restore 612, 618
        }
    }
}
