global using CustomCADs.Carts.Application.ActiveCarts.Dtos;
global using CustomCADs.Carts.Application.PurchasedCarts.Dtos;
global using CustomCADs.Carts.Domain.ActiveCarts;
global using CustomCADs.Carts.Domain.PurchasedCarts;
global using CustomCADs.Shared.Abstractions.Requests.Commands;
global using CustomCADs.Shared.Abstractions.Requests.Queries;
global using CustomCADs.Shared.Core;
global using CustomCADs.Shared.Core.Common.Exceptions.Application;
global using CustomCADs.Shared.Core.Common.TypedIds.Carts;