global using CustomCADs.Carts.Application.ActiveCarts.Dtos;
global using CustomCADs.Carts.Application.PurchasedCarts.Dtos;
global using CustomCADs.Carts.Domain.ActiveCarts;
global using CustomCADs.Carts.Domain.PurchasedCarts;
global using CustomCADs.Shared.Application.Abstractions.Requests.Commands;
global using CustomCADs.Shared.Application.Abstractions.Requests.Queries;
global using CustomCADs.Shared.Application.Exceptions;
global using CustomCADs.Shared.Domain;
global using CustomCADs.Shared.Domain.TypedIds.Carts;
