// <auto-generated />
using System;
using System.Collections.Generic;
using CustomCADs.Cads.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomCADs.Cads.Persistence.Migrations
{
    [DbContext(typeof(CadsContext))]
    [Migration("20241120175238_Updated_Cad_Again")]
    partial class Updated_Cad_Again
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Cads")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomCADs.Cads.Domain.Cads.Cad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Key");

                    b.ComplexProperty<Dictionary<string, object>>("CamCoordinates", "CustomCADs.Cads.Domain.Cads.Cad.CamCoordinates#Coordinates", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("X")
                                .HasColumnType("int")
                                .HasColumnName("CamX");

                            b1.Property<int>("Y")
                                .HasColumnType("int")
                                .HasColumnName("CamY");

                            b1.Property<int>("Z")
                                .HasColumnType("int")
                                .HasColumnName("CamZ");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PanCoordinates", "CustomCADs.Cads.Domain.Cads.Cad.PanCoordinates#Coordinates", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("X")
                                .HasColumnType("int")
                                .HasColumnName("PanX");

                            b1.Property<int>("Y")
                                .HasColumnType("int")
                                .HasColumnName("PanY");

                            b1.Property<int>("Z")
                                .HasColumnType("int")
                                .HasColumnName("PanZ");
                        });

                    b.HasKey("Id");

                    b.ToTable("Cads", "Cads");
                });
#pragma warning restore 612, 618
        }
    }
}
