// <auto-generated />
using System;
using System.Collections.Generic;
using CustomCADs.Files.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomCADs.Files.Persistence.Migrations
{
    [DbContext(typeof(FilesContext))]
    [Migration("20241218105858_Initial_Migration")]
    partial class Initial_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Files")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomCADs.Files.Domain.Cads.Cad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Key");

                    b.ComplexProperty<Dictionary<string, object>>("CamCoordinates", "CustomCADs.Files.Domain.Cads.Cad.CamCoordinates#Coordinates", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("X")
                                .HasColumnType("integer")
                                .HasColumnName("CamX");

                            b1.Property<int>("Y")
                                .HasColumnType("integer")
                                .HasColumnName("CamY");

                            b1.Property<int>("Z")
                                .HasColumnType("integer")
                                .HasColumnName("CamZ");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PanCoordinates", "CustomCADs.Files.Domain.Cads.Cad.PanCoordinates#Coordinates", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("X")
                                .HasColumnType("integer")
                                .HasColumnName("PanX");

                            b1.Property<int>("Y")
                                .HasColumnType("integer")
                                .HasColumnName("PanY");

                            b1.Property<int>("Z")
                                .HasColumnType("integer")
                                .HasColumnName("PanZ");
                        });

                    b.HasKey("Id");

                    b.ToTable("Cads", "Files");
                });

            modelBuilder.Entity("CustomCADs.Files.Domain.Images.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ContentType");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Key");

                    b.HasKey("Id");

                    b.ToTable("Images", "Files");
                });
#pragma warning restore 612, 618
        }
    }
}
