global using CustomCADs.Accounts.Application.Common.Caching.Roles;
global using CustomCADs.Accounts.Application.Common.Dtos;
global using CustomCADs.Accounts.Domain.Accounts;
global using CustomCADs.Accounts.Domain.Roles;
global using CustomCADs.Shared.Abstractions.Requests.Commands;
global using CustomCADs.Shared.Abstractions.Requests.Queries;
global using CustomCADs.Shared.Core;
global using CustomCADs.Shared.Core.Common.Exceptions.Application;
global using CustomCADs.Shared.Core.Common.TypedIds.Accounts;