global using CustomCADs.Accounts.Application.Roles.Dtos;
global using CustomCADs.Accounts.Domain.Accounts;
global using CustomCADs.Accounts.Domain.Roles;
global using CustomCADs.Shared.Abstractions.Cache;
global using CustomCADs.Shared.Abstractions.Requests.Commands;
global using CustomCADs.Shared.Abstractions.Requests.Queries;
global using CustomCADs.Shared.Core;
global using CustomCADs.Shared.Core.Common.Exceptions.Application;
global using CustomCADs.Shared.Core.Common.TypedIds.Accounts;
