name: Continuous Delivery pipeline

on:
  workflow_run:
    workflows: Continuous Integration pipeline
    types: completed
    branches: main

jobs:
  deliver:
    if: github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/deliver-ecr.yml
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
