name: Universal Integration pipeline

on:
  push:
    branches: 
      - feature/*
      - release/*
      - hotfix/*
    tags-ignore: 
      - 'v*.*.*'

jobs:
  build:
    uses: ./.github/workflows/build-dotnet.yml
  unit_test:
    needs: build
    uses: ./.github/workflows/unit-test.yml
