name: Universal Integration pipeline

on:
  workflow_call:
  push:
    branches: 
      - feature/*
      - hotfix/*
    tags-ignore: 
      - 'v*.*.*'

jobs:
  unit_test:
    uses: ./.github/workflows/unit-test.yml
