name: Main Delivery pipeline

on:
  workflow_dispatch:
  push:
    branches: main
    tags-ignore: 'v*.*.*'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  deliver:
    needs: ci
    uses: ./.github/workflows/production-delivery.yml
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
      aws-ecr-registry: ${{ secrets.AWS_ECR_REGISTRY }}
