name: Release Delivery pipeline

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Continuous Integration pipeline]
    types: completed
    branches: release/*

jobs:
  deliver:
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/staging-delivery.yml
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
      aws-ecr-registry: ${{ secrets.AWS_ECR_REGISTRY }}
