name: Release Delivery pipeline

on:
  workflow_dispatch:
  push:
    branches: release/*

jobs:
  deliver:
    uses: ./.github/workflows/staging-delivery.yml
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
      aws-ecr-registry: ${{ secrets.AWS_ECR_REGISTRY }}
