name: Run .NET Unit Tests Action

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Run Unit Tests
        working-directory: ./test/UnitTests
        run: dotnet test ../../CustomCADs.sln --no-build --configuration Release --logger "trx;LogFileName=unit-tests.trx"