name: Enforce Semantic Versioning Tag

on:
  pull_request:
    branches: [main]

jobs:
  tag_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Obtain Git Version tag
        run: |
          VERSION=$(git tag --points-at=${{ github.event.pull_request.head.sha }} || echo "")
          if [ -z "$VERSION" ]; then
              echo "Error: No tags found at this commit."
              exit 1
          else 
              echo "VERSION=$VERSION" >> $GITHUB_ENV
          fi

      - name: Ensure correctly formatted Version tag
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          if [[ "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Version tag exists: $VERSION"
          else
              echo "Error: Invalid version tag. Please tag the commit with a version number following the format 'vX.Y.Z'."
              exit 1
          fi
